import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'inc-vesting-table',
  templateUrl: './vesting-table.component.html',
  styleUrls: ['./vesting-table.component.scss']
})
export class VestingTableComponent implements OnInit {
  cols = [
    { field: 'column1', header: 'Vin' },
    { field: 'column2', header: 'Year' },
    { field: 'column3', header: 'Brand' },
    { field: 'column4', header: 'Color' },
    { field: 'column5', header: 'Color' },
    { field: 'column6', header: 'Color' },
    { field: 'column7', header: 'Color' },
    { field: 'column8', header: 'Color' },
    { field: 'column9', header: 'Color' },
    { field: 'column10', header: 'Color' },
  ];
  data;

  constructor() { }

  ngOnInit(): void {
    this.data = [{column1: 'asdfasdfasdf',
      column2: 'asdfasdfasdf',
      column3: 'asdfasdfasdf',
      column4: 'asdfasdfasdf',
      column5: 'asdfasdfasdf',
      column6: 'asdfasdfasdf',
      column7: 'asdfasdfasdf',
      column8: 'asdfasdfasdf',
      column9: 'asdfasdfasdf',
      column10: 'asdfasdfasdf'},
      {column1: 'asdfasdfasdf',
        column2: 'asdfasdfasdf',
        column3: 'asdfasdfasdf',
        column4: 'asdfasdfasdf',
        column5: 'asdfasdfasdf',
        column6: 'asdfasdfasdf',
        column7: 'asdfasdfasdf',
        column8: 'asdfasdfasdf',
        column9: 'asdfasdfasdf',
        column10: 'asdfasdfasdf'},
      {column1: 'asdfasdfasdf',
        column2: 'asdfasdfasdf',
        column3: 'asdfasdfasdf',
        column4: 'asdfasdfasdf',
        column5: 'asdfasdfasdf',
        column6: 'asdfasdfasdf',
        column7: 'asdfasdfasdf',
        column8: 'asdfasdfasdf',
        column9: 'asdfasdfasdf',
        column10: 'asdfasdfasdf'},
      {column1: 'asdfasdfasdf',
        column2: 'asdfasdfasdf',
        column3: 'asdfasdfasdf',
        column4: 'asdfasdfasdf',
        column5: 'asdfasdfasdf',
        column6: 'asdfasdfasdf',
        column7: 'asdfasdfasdf',
        column8: 'asdfasdfasdf',
        column9: 'asdfasdfasdf',
        column10: 'asdfasdfasdf'},
      {column1: 'asdfasdfasdf',
        column2: 'asdfasdfasdf',
        column3: 'asdfasdfasdf',
        column4: 'asdfasdfasdf',
        column5: 'asdfasdfasdf',
        column6: 'asdfasdfasdf',
        column7: 'asdfasdfasdf',
        column8: 'asdfasdfasdf',
        column9: 'asdfasdfasdf',
        column10: 'asdfasdfasdf'},
      {column1: 'asdfasdfasdf',
        column2: 'asdfasdfasdf',
        column3: 'asdfasdfasdf',
        column4: 'asdfasdfasdf',
        column5: 'asdfasdfasdf',
        column6: 'asdfasdfasdf',
        column7: 'asdfasdfasdf',
        column8: 'asdfasdfasdf',
        column9: 'asdfasdfasdf',
        column10: 'asdfasdfasdf'},
      {column1: 'asdfasdfasdf',
        column2: 'asdfasdfasdf',
        column3: 'asdfasdfasdf',
        column4: 'asdfasdfasdf',
        column5: 'asdfasdfasdf',
        column6: 'asdfasdfasdf',
        column7: 'asdfasdfasdf',
        column8: 'asdfasdfasdf',
        column9: 'asdfasdfasdf',
        column10: 'asdfasdfasdf'},
      {column1: 'asdfasdfasdf',
        column2: 'asdfasdfasdf',
        column3: 'asdfasdfasdf',
        column4: 'asdfasdfasdf',
        column5: 'asdfasdfasdf',
        column6: 'asdfasdfasdf',
        column7: 'asdfasdfasdf',
        column8: 'asdfasdfasdf',
        column9: 'asdfasdfasdf',
        column10: 'asdfasdfasdf'},
      {column1: 'asdfasdfasdf',
        column2: 'asdfasdfasdf',
        column3: 'asdfasdfasdf',
        column4: 'asdfasdfasdf',
        column5: 'asdfasdfasdf',
        column6: 'asdfasdfasdf',
        column7: 'asdfasdfasdf',
        column8: 'asdfasdfasdf',
        column9: 'asdfasdfasdf',
        column10: 'asdfasdfasdf'},
      {column1: 'asdfasdfasdf',
        column2: 'asdfasdfasdf',
        column3: 'asdfasdfasdf',
        column4: 'asdfasdfasdf',
        column5: 'asdfasdfasdf',
        column6: 'asdfasdfasdf',
        column7: 'asdfasdfasdf',
        column8: 'asdfasdfasdf',
        column9: 'asdfasdfasdf',
        column10: 'asdfasdfasdf'},];
  }

}
